export const FONT_FAMILY_GROUPS = [
  {
    label: "Sans-Serif",
    fonts: [
      "Roboto",
      "Open Sans",
      "Lato",
      "Inter",
      "Source Sans 3",
      "Noto Sans",
      "Poppins",
      "Raleway",
      "Work Sans",
      "Nunito",
      "Rubik",
      "DM Sans",
      "Outfit",
      "Plus Jakarta Sans",
      "Figtree",
      "Quicksand",
      "Cabin",
      "Karla",
      "Mukta",
      "Exo 2",
      "Titillium Web",
      "Mulish",
      "Barlow",
      "PT Sans",
      "Ubuntu",
      "Fira Sans",
      "Lexend",
      "Manrope",
    ],
  },
  {
    label: "Display / Headlines",
    fonts: [
      "Montserrat",
      "Oswald",
      "Roboto Condensed",
      "Fjalla One",
      "Bebas Neue",
      "Sora",
      "Anton",
      "Archivo Black",
      "Righteous",
      "Passion One",
      "Alfa Slab One",
      "Bangers",
      "Permanent Marker",
      "Black Ops One",
      "Russo One",
      "Kanit",
      "Saira Condensed",
      "Teko",
      "Archivo",
      "Staatliches",
      "Big Shoulders Display",
    ],
  },
  {
    label: "Serif",
    fonts: [
      "Playfair Display",
      "Lora",
      "Cormorant Garamond",
      "Merriweather",
      "Libre Baskerville",
      "Crimson Text",
      "Bitter",
      "Alegreya",
      "Play",
      "PT Serif",
      "Noto Serif",
      "Source Serif 4",
      "Roboto Slab",
      "DM Serif Display",
      "Libre Caslon Text",
      "EB Garamond",
      "Vollkorn",
      "Spectral",
      "Cardo",
      "Cinzel",
      "Old Standard TT",
    ],
  },
  {
    label: "Script / Handwriting",
    fonts: [
      "Dancing Script",
      "Pacifico",
      "Great Vibes",
      "Tangerine",
      "Satisfy",
      "Lobster",
      "Lobster Two",
      "Sacramento",
      "Kaushan Script",
      "Caveat",
      "Shadows Into Light",
      "Indie Flower",
      "Amatic SC",
      "Allura",
      "Cookie",
      "Courgette",
      "Playball",
      "Alex Brush",
      "Rouge Script",
      "Marck Script",
    ],
  },
  {
    label: "Monospace",
    fonts: [
      "Roboto Mono",
      "Source Code Pro",
      "Fira Code",
      "JetBrains Mono",
      "IBM Plex Mono",
      "Space Mono",
      "Inconsolata",
    ],
  },
  {
    label: "Malayalam",
    fonts: [
      "Chilanka",
      "Manjari",
      "Baloo Chettan 2",
      "Anek Malayalam",
      "Arima",
      "Gayathri",
      "Noto Serif Malayalam",
      "Noto Sans Malayalam",
    ],
  },
  {
    label: "Special / Fun",
    fonts: [
      "Josefin Sans",
      "IBM Plex Sans",
      "Space Grotesk",
      "Comfortaa",
      "Varela Round",
      "Fredoka",
      "Baloo 2",
      "Patrick Hand",
      "Architects Daughter",
      "Gloria Hallelujah",
      "Orbitron",
      "Press Start 2P",
    ],
  },
];

export const COMMON_GOOGLE_FONTS_URL =
  "https://fonts.googleapis.com/css2?family=Baloo+Chettan+2:wght@400;500;600;700;800&family=Bebas+Neue&family=Fjalla+One&family=Inter:wght@400;500;600;700;800&family=Montserrat:wght@400;500;600;700;800&family=Noto+Sans+Malayalam:wght@400;500;600;700;800&family=Noto+Serif+Malayalam:wght@400;500;600;700;800&family=Open+Sans:wght@400;500;600;700;800&family=Poppins:wght@400;500;600;700;800&family=Roboto:wght@400;500;700;900&display=swap";
